# coding: utf-8

"""
    Marquez

    Marquez is an open source **metadata service** for the **collection**, **aggregation**, and **visualization** of a data ecosystem's metadata.  # noqa: E501

    OpenAPI spec version: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import marquez_client
from marquez_client.models.create_job import CreateJob  # noqa: E501
from marquez_client.rest import ApiException


class TestCreateJob(unittest.TestCase):
    """CreateJob unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateJob(self):
        """Test CreateJob"""
        # FIXME: construct object with mandatory attributes with example values
        # model = marquez_client.models.create_job.CreateJob()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
