# coding: utf-8

"""
    Marquez

    Marquez is an open source **metadata service** for the **collection**, **aggregation**, and **visualization** of a data ecosystem's metadata.  # noqa: E501

    OpenAPI spec version: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.inline_object2 import InlineObject2  # noqa: E501
from openapi_client.rest import ApiException


class TestInlineObject2(unittest.TestCase):
    """InlineObject2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineObject2(self):
        """Test InlineObject2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.inline_object2.InlineObject2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
