version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - "dependencies"
      - "dependabot"

  - package-ecosystem: "gradle"
    directory: "clients/java"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - "dependencies"
      - "dependabot"

  - package-ecosystem: "gradle"
    directory: "web"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - "dependencies"
      - "dependabot"

  - package-ecosystem: "gradle"
    directory: "api"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - "dependencies"
      - "dependabot"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - "dependencies"
      - "dependabot"
