FROM python:3.6-slim
RUN mkdir /app
RUN mkdir /common
ADD airflow/setup.py /app
ADD airflow/README.md /app
COPY common/ /common
RUN (cd common && python setup.py install --user)
COPY airflow/marquez_airflow /app/marquez_airflow
WORKDIR /app
RUN ls -la
RUN pip wheel --no-deps --wheel-dir=/app/wheel .[tests]
RUN cp -R /app/wheel /whl
