FROM python:3.6-slim
RUN mkdir /app
RUN apt-get update && \
    apt-get install -y git
ADD airflow/setup.py /app
ADD airflow/README.md /app
COPY airflow/marquez_airflow /app/marquez_airflow
WORKDIR /app
RUN ls -la
RUN pip wheel --wheel-dir=/app/wheel -e .[tests]
RUN cp -R /app/wheel /whl
