tasks:
  - init: |
      docker-compose pull
  - command: |
      ./docker/up.sh --build --seed
ports:
  - port: 3000
    onOpen: open-browser
  - port: 5000
    onOpen: ignore
  - port: 5001
    onOpen: ignore
  - port: 5432
    onOpen: ignore
  onOpen: ignore
vscode:
  extensions:
    - ms-azuretools.vscode-docker

