tasks:
  - command: |
      DOCKER_BUILDKIT=1 ./docker/up.sh --seed
ports:
  - port: 3000
    visibility: public
    onOpen: open-browser
  - port: 5000
    onOpen: ignore
  - port: 5001
    onOpen: ignore
  - port: 5432
    onOpen: ignore
vscode:
  extensions:
    - ms-azuretools.vscode-docker

