tasks:
  - init: |
      API_PORT=5000 API_ADMIN_PORT=5001 WEB_PORT=3000 docker-compose pull
  - command: |
      ./docker/up.sh --build --seed
ports:
  - port: 3000
    onOpen: open-browser
  - port: 5000
    onOpen: ignore
  - port: 5001
    onOpen: ignore
  - port: 5432
    onOpen: ignore
github:
  prebuilds:
    master: true
    addCheck: prevent-merge-on-error
vscode:
  extensions:
    - ms-azuretools.vscode-docker

