repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-added-large-files

  -   repo: https://github.com/jguttman94/pre-commit-gradle
      rev: v0.3.0
      hooks:
        -  id: gradle-spotless
           args: ['-w', --wrapper]
