server:
  applicationConnectors:
  - type: http
    port: ${MARQUEZ_PORT:-5000}
    httpCompliance: RFC7230_LEGACY
  adminConnectors:
  - type: http
    port: ${MARQUEZ_ADMIN_PORT:-5001}

db:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://host.docker.internal:60901/marquez_preprod
  user: marquez_preprod
  password: ${POSTGRES_PASSWORD}

migrateOnStartup: true

graphql:
  enabled: true

logging:
  level: INFO
  appenders:
    - type: console

tags:
  - name: PII
    description: Personally identifiable information
  - name: SENSITIVE
    description: Contains sensitive information

exclude:
  namespaces:
    onRead:
      enabled: true
      pattern: '.*[!@#$%^&*()+=\[\]{};\|,<>?].*|^\/.*|^$'

metrics:
  frequency: ${METRICS_FREQUENCY:-1 minute}
  reporters:
    - type: console
      timeZone: UTC
      output: stdout