version: "3.7"
services:
  api:
    image: "marquezproject/marquez:${TAG}"
    container_name: marquez-api
    environment:
      - MARQUEZ_PORT=${API_PORT}
      - MARQUEZ_ADMIN_PORT=${API_ADMIN_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
      - "${API_ADMIN_PORT}:${API_ADMIN_PORT}"
    volumes:
      - data:/opt/marquez
    links:
      - "db:postgres"
      - opensearch
    depends_on:
      - opensearch
      - db
    entrypoint:
      - /opt/marquez/wait-for-it.sh
      - db:${POSTGRES_PORT}
      - --
      - /opt/marquez/wait-for-it.sh
      - opensearch:${SEARCH_PORT}
      - --
      - ./entrypoint.sh
    networks:
      - opensearch-net

  db:
    image: postgres:14
    container_name: marquez-db
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - MARQUEZ_DB=marquez
      - MARQUEZ_USER=marquez
      - MARQUEZ_PASSWORD=marquez
    volumes:
      - db-conf:/etc/postgresql
      - db-init:/docker-entrypoint-initdb.d
      - db-backup:/var/lib/postgresql/data
    command: [ "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf" ]
    # Enables SQL statement logging (see: https://www.postgresql.org/docs/12/runtime-config-logging.html#GUC-LOG-STATEMENT)
    # command: ["postgres", "-c", "log_statement=all"]
    networks:
      - opensearch-net

  opensearch:
    image: opensearchproject/opensearch:2.5.0
    container_name: opensearch
    hostname: opensearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch
      - discovery.seed_hosts=opensearch
      - cluster.initial_cluster_manager_nodes=opensearch
      - bootstrap.memory_lock=true
      - plugins.security.ssl.http.enabled=false
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_PASSWORD=admin
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    cap_add:
      - IPC_LOCK
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - opensearch-net

  web:
    networks:
      - opensearch-net

  seed_marquez:
    depends_on:
      - opensearch

volumes:
  data:
  opensearch-data:
  db-conf:
  db-init:
  db-backup:

networks:
  opensearch-net:
