version: "3.7"
services:
  db:
    image: postgres:12.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - MARQUEZ_DB=marquez
      - MARQUEZ_USER=buendia
      - MARQUEZ_PASSWORD=macondo
    volumes:
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
