apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "marquez.fullname" . }}-api
  labels:
    app.kubernetes.io/name: {{ include "marquez.name" . }}
    helm.sh/chart: {{ include "marquez.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.marquez.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "marquez.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "marquez.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: api
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.marquez.image.repository }}:{{ .Values.marquez.image.tag }}"
          imagePullPolicy: {{ .Values.marquez.image.pullPolicy }}
          volumeMounts:
            - name: marquez-volume
              mountPath: /usr/src/app/config.yml
              subPath: config.yml
          ports:
            - name: http
              containerPort: {{ .Values.marquez.port }} 
              protocol: TCP
            - name: http-admin
              containerPort: {{ .Values.marquez.adminPort }} 
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http-admin
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http-admin
          env:
            - name: MARQUEZ_PORT
              value: {{ .Values.marquez.port | quote }}
            - name: MARQUEZ_ADMIN_PORT
              value: {{ .Values.marquez.adminPort | quote }}
            - name: MARQUEZ_CONFIG
              value: /usr/src/app/config.yml
            - name: POSTGRES_HOST
              value: {{ .Values.marquez.db.host | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.marquez.db.port | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.marquez.db.name }}
            - name: POSTGRES_USER
              value: {{ .Values.marquez.db.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.marquez.db.password }}
            - name: MIGRATE_ON_STARTUP
              value: {{ .Values.marquez.migrateOnStartup | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: marquez-volume
          configMap:
            name: {{ template "marquez.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}