{{- if .Values.web.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "marquez.fullname" . }}-web
  labels:
    app.kubernetes.io/name: {{ include "marquez.name" . }}
    helm.sh/chart: {{ include "marquez.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
 
  selector:
    app.kubernetes.io/name: {{ include "marquez.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: web
{{- end }}