version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.8.5
  working_directory: ~/marquez-airflow
  environment:
    SLUGIFY_USES_TEXT_UNIDECODE: 'yes'

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install airflow from package
          command: pip install --user -e .
      - run: pip install --user flake8
      - run: python -m flake8 --exclude integration

  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install test dependencies
          command: pip install --user -r test-requirements.txt --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-1.10.12/constraints-3.7.txt"
      - run:
          name: Setup Airflow DB
          command: airflow initdb
      - run:
          name: Install marquez-airflow package
          command: pip install --user -e .
      - run:
          name:
          environment:
            AIRFLOW__CORE__DAGS_FOLDER: './tests/test_dags'
          command: python -m pytest --ignore=tests/integration --cov=marquez_airflow tests/
      - run: bash <(curl -s https://codecov.io/bash)

  integration:
    working_directory: ~/marquez-airflow/tests/integration
    machine: true
    steps:
      - checkout:
          path: ~/marquez-airflow
      - run: ./../../.circleci/get-docker-compose.sh
      - run: ./docker/up.sh

  release:
    <<: *defaults
    steps:
      - checkout
      - run: ./.circleci/release_check.sh
      - run: pip install --user twine
      - run: python setup.py sdist
      - run: python -m twine upload --verbose dist/*

workflows:
  version: 2
  marquez_airflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - integration:
          requires:
            - test
      - release:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}$/
            branches:
              ignore: /.*/
