# coding: utf-8

"""
    Marquez

    Marquez is an open source **metadata service** for the **collection**, **aggregation**, and **visualization** of a data ecosystem's metadata.  # noqa: E501

    OpenAPI spec version: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class Namespace(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'created_at': 'datetime',
        'owner': 'str',
        'description': 'str'
    }

    attribute_map = {
        'name': 'name',
        'created_at': 'createdAt',
        'owner': 'owner',
        'description': 'description'
    }

    def __init__(self, name=None, created_at=None, owner=None, description=None):  # noqa: E501
        """Namespace - a model defined in OpenAPI"""  # noqa: E501

        self._name = None
        self._created_at = None
        self._owner = None
        self._description = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if created_at is not None:
            self.created_at = created_at
        if owner is not None:
            self.owner = owner
        if description is not None:
            self.description = description

    @property
    def name(self):
        """Gets the name of this Namespace.  # noqa: E501

        The name of the namespace.  # noqa: E501

        :return: The name of this Namespace.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Namespace.

        The name of the namespace.  # noqa: E501

        :param name: The name of this Namespace.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def created_at(self):
        """Gets the created_at of this Namespace.  # noqa: E501

        An [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) timestamp representing the date/time the namespace was created.  # noqa: E501

        :return: The created_at of this Namespace.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this Namespace.

        An [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) timestamp representing the date/time the namespace was created.  # noqa: E501

        :param created_at: The created_at of this Namespace.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def owner(self):
        """Gets the owner of this Namespace.  # noqa: E501

        The owner of the namespace.  # noqa: E501

        :return: The owner of this Namespace.  # noqa: E501
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this Namespace.

        The owner of the namespace.  # noqa: E501

        :param owner: The owner of this Namespace.  # noqa: E501
        :type: str
        """

        self._owner = owner

    @property
    def description(self):
        """Gets the description of this Namespace.  # noqa: E501

        The description of the namespace.  # noqa: E501

        :return: The description of this Namespace.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Namespace.

        The description of the namespace.  # noqa: E501

        :param description: The description of this Namespace.  # noqa: E501
        :type: str
        """

        self._description = description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Namespace):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
