version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.6
  working_directory: ~/marquez_python


jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: pip install --user coverage
      - run: pip install --user -e .
      - run: pip install --user flake8
      - run: python -m flake8 --extend-ignore=F401

  test:
    <<: *defaults
    steps:
      - checkout
      - run: pip install --user  -r test-requirements.txt
      - run: python -m pytest --cov=marquez_python tests/
      - run: bash <(curl -s https://codecov.io/bash)

  release:
    <<: *defaults
    working_directory: ~/marquez_python
    steps:
      - checkout
      - run: ./.circleci/release_check.sh
      - run: pip install --user twine
      - run: python setup.py sdist
      - run: python -m twine upload --verbose dist/*

workflows:
  version: 2
  marquez_python:
    jobs:
      - build
      - test:
          requires:
            - build
      - release:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
            branches:
              ignore: /.*/
