#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username ${POSTGRES_USER} <<-EOSQL
	CREATE USER ${MARQUEZ_API_USER};
	ALTER USER ${MARQUEZ_API_USER} WITH PASSWORD '${MARQUEZ_API_PASSWORD}';
	CREATE DATABASE ${MARQUEZ_DB_NAME};
	GRANT ALL PRIVILEGES ON DATABASE ${MARQUEZ_DB_NAME} TO ${MARQUEZ_API_USER};
EOSQL
