#!/bin/bash
#
# Usage: $ ./init-db.sh

set -eu

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" > /dev/null <<-EOSQL
  CREATE USER ${MARQUEZ_USER};
  ALTER USER ${MARQUEZ_USER} WITH PASSWORD '${MARQUEZ_PASSWORD}';
  CREATE DATABASE ${MARQUEZ_DB_NAME};
  GRANT ALL PRIVILEGES ON DATABASE ${MARQUEZ_DB_NAME} TO ${MARQUEZ_USER};
EOSQL
