{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "marquez.postgresql.secretName" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: {{ .Values.externalSecrets.secretStoreKind | default "SecretStore" }}
  target:
    name: {{ include "marquez.postgresql.secretName" . }}
    creationPolicy: Owner
  data:
  - secretKey: {{ include "marquez.database.existingsecret.key" . }}
    remoteRef:
      key: {{ .Values.externalSecrets.auth.password.remoteKey }}
      {{- if .Values.externalSecrets.auth.password.remoteProperty }}
      property: {{ .Values.externalSecrets.auth.password.remoteProperty }}
      {{- end }}
{{- end -}}
