version: "3.7"
services:
  notebook:
    image: jupyter/pyspark-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./docker/notebooks:/home/jovyan/notebooks
      - ./integrations/spark/build:/home/jovyan/marquezlib
    links:
      - "api:marquez"
    depends_on:
      - api
