# coding: utf-8

"""
    Marquez

    Marquez is an open source **metadata service** for the **collection**, **aggregation**, and **visualization** of a data ecosystem's metadata.  # noqa: E501

    OpenAPI spec version: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class CreateJobRun(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'nominal_start_time': 'datetime',
        'nominal_end_time': 'datetime',
        'run_args': 'str'
    }

    attribute_map = {
        'nominal_start_time': 'nominalStartTime',
        'nominal_end_time': 'nominalEndTime',
        'run_args': 'runArgs'
    }

    def __init__(self, nominal_start_time=None, nominal_end_time=None, run_args=None):  # noqa: E501
        """CreateJobRun - a model defined in OpenAPI"""  # noqa: E501

        self._nominal_start_time = None
        self._nominal_end_time = None
        self._run_args = None
        self.discriminator = None

        if nominal_start_time is not None:
            self.nominal_start_time = nominal_start_time
        if nominal_end_time is not None:
            self.nominal_end_time = nominal_end_time
        if run_args is not None:
            self.run_args = run_args

    @property
    def nominal_start_time(self):
        """Gets the nominal_start_time of this CreateJobRun.  # noqa: E501

        The nominal start time of the job.  # noqa: E501

        :return: The nominal_start_time of this CreateJobRun.  # noqa: E501
        :rtype: datetime
        """
        return self._nominal_start_time

    @nominal_start_time.setter
    def nominal_start_time(self, nominal_start_time):
        """Sets the nominal_start_time of this CreateJobRun.

        The nominal start time of the job.  # noqa: E501

        :param nominal_start_time: The nominal_start_time of this CreateJobRun.  # noqa: E501
        :type: datetime
        """

        self._nominal_start_time = nominal_start_time

    @property
    def nominal_end_time(self):
        """Gets the nominal_end_time of this CreateJobRun.  # noqa: E501

        The nominal end time of the job.  # noqa: E501

        :return: The nominal_end_time of this CreateJobRun.  # noqa: E501
        :rtype: datetime
        """
        return self._nominal_end_time

    @nominal_end_time.setter
    def nominal_end_time(self, nominal_end_time):
        """Sets the nominal_end_time of this CreateJobRun.

        The nominal end time of the job.  # noqa: E501

        :param nominal_end_time: The nominal_end_time of this CreateJobRun.  # noqa: E501
        :type: datetime
        """

        self._nominal_end_time = nominal_end_time

    @property
    def run_args(self):
        """Gets the run_args of this CreateJobRun.  # noqa: E501

        The runtime arguments of the job. JSON encoded.  # noqa: E501

        :return: The run_args of this CreateJobRun.  # noqa: E501
        :rtype: str
        """
        return self._run_args

    @run_args.setter
    def run_args(self, run_args):
        """Sets the run_args of this CreateJobRun.

        The runtime arguments of the job. JSON encoded.  # noqa: E501

        :param run_args: The run_args of this CreateJobRun.  # noqa: E501
        :type: str
        """

        self._run_args = run_args

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateJobRun):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
