# ...
name: db

on:
  # Triggers the workflow on push or pull request events but only for the 'main' branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# ...
jobs:
  migrations:
    name: Run db migrations
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run db-migration.sh on latest db schema with latest migrations
      run: sudo ./.github/workflows/db-migration.sh
