version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile 
      args:
        REACT_APP_ADVANCED_SEARCH: ${REACT_APP_ADVANCED_SEARCH}
        REACT_APP_OKTA_CLIENT_ID: ${REACT_APP_OKTA_CLIENT_ID}
        REACT_APP_OKTA_ISSUER: ${REACT_APP_OKTA_ISSUER}
    container_name: marquez-web
    environment:
      - MARQUEZ_HOST=marquez-api
      - MARQUEZ_PORT=5000
      - WEB_PORT=3000
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - tabajara

networks:
  tabajara:
    driver: bridge